Entity/ApplicationRepository.php

Just list applications by alphabetic order in the toolbar

list application by alphabetic order

---

Resources/views/Customer/form.html.twig
Resources/views/Sam/index.html.twig
Resources/views/bootstrap_extension_list.html.twig
Resources/views/form/generic_list.html.twig
Resources/views/generic_list.html.twig

https://github.com/CanalTP/NmmPortalBundle/issues/29

twig: fix base default views extending

---

DataFixtures/ORM/UserTrait.php
Migrations/pdo_pgsql/Version010.php
composer.json

Moving migration from sam-ecore-user-management to sam-ecore
[https://github.com/CanalTP/NMM/pull/263](https://github.com/CanalTP/NMM/pull/263)

Moving timezone migration from SamEcoreUserManagement

---

Features/Context/DoctrineDbalContext.php

add update possibiliy in dbal context (can be used in behat)

add update possibiliy in dbal context

---

Component/BusinessComponent.php
Resources/config/permissions.yml

This will remove the navitia.io tab from NMM admin.
This feature is completely useless!
A PR on NmmPortalBundle will do some cleanup.

Remove useless navitia.io feature

---

Resources/views/base.html.twig

This PR add two blocks for analytics part.

Refs #RZO_413 ~ Twig blocks added for google analytics.

---

Component/BusinessComponent.php
Resources/translations/messages.fr.yml
Resources/views/base.html.twig

Accpetable display in admin NMM
Issues
GN-55
to check go in admin on every page, see difference
https://github.com/CanalTP/NMM/issues/338

Display gn 55 improvements

---

Form/Type/CustomerType.php
Resources/views/Customer/form.html.twig

ID Client readonly on edition
BOT-359

ID Client readonly

---

Resources/views/base.html.twig
Resources/views/datalayer_user.js.twig

This PR implement datalayer for user usage.
https://github.com/CanalTP/NMM/issues/340

Refs #BOT-408 ~ Datalayer implemented

---

Resources/config/permissions.yml
Resources/translations/messages.fr.yml

This PR resolves wordings in admin permission
Into NMM admin,
See permission wordings

Wordings admin permission

---

Resources/views/base.html.twig
Resources/views/datalayer_user.html.twig
Resources/views/datalayer_user.js.twig

Hi,
As the issue https://github.com/CanalTP/SamCoreBundle/issues/48 didn't find a reviewer I did some changes in order to clean the dataLayer issue with a simple check.
I also renamed the template file as it isn't a js file but html one.
I hope @Netmisa  you'll agree with that.
Thank you.
fix https://github.com/CanalTP/SamCoreBundle/issues/48

remove js error with datalayer

---

Migrations/pdo_pgsql/Version011.php
Resources/views/datalayer_user.html.twig

:warning: This PR depends on https://github.com/CanalTP/SamEcoreUserManagerBundle/pull/26
This PR pushes TR user datas in datalayer
This is new feature
Here are the following steps to test this pull request:
- Check exposed data in HTML code source when user isn't authenticated
- Check exposed data in HTML code source when user is authenticated

Feature bot 590 datalayer for traffic repport

---

Entity/CustomerRepository.php

This PR fix the navitia get unknow coverage error when generate line cache
Reference link: BOT-1151
Here are the following steps to test this pull request:
- change one client locked field to "true"
- call `php app/console realtime:cache:lines -vvv` in nmm
- you should not see your client in the output
Mention here the people who should review your PR

Do not return locked client

---

Resources/translations/messages.en.yml

I create new file `messages.en.yml` to add some footer words translation

Refs #BOT-1463 ~ Add en translations.

---

Resources/config/routing.yml

see https://github.com/CanalTP/SamCoreBundle/pull/61

Delete entry of deleted file

---

Resources/views/base.html.twig

This PR fix the position of the modal when it display on the page.
BOT-1717

Update position of modal to fix the display

---

Migrations/pdo_pgsql/Version013.php

This PR adds migration script to make customer field required for t_user_usr

#BOT-1922 - Make customer field required for t_user_usr

---

Resources/config/services.yml
Resources/translations/messages.en.yml
Resources/translations/messages.fr.yml
Resources/views/Email/base.html.twig
Resources/views/Email/deletion.html.twig
Resources/views/Email/warning.html.twig
Services/GDPR/HandlerInterface.php
Services/GDPR/Notifier/Deletion.php
Services/GDPR/Notifier/Nothing.php
Services/GDPR/Notifier/Notifier.php
Services/GDPR/Notifier/Reset.php
Services/GDPR/Notifier/SuperAdmin.php
Services/GDPR/Notifier/Warning.php
Tests/Unit/Services/GDPR/GdprTestCase.php
Tests/Unit/Services/GDPR/Notifier/NothingTest.php

This PR fixes the case when an user has no customer in GDPR service
:warning:  depends on:
- https://github.com/CanalTP/MediaDeployApp/pull/609
- https://github.com/CanalTP/NMM/pull/415

Handling case when user has no customer in gdpr service

---

Event/SamCoreEvents.php

Add event on user edit

---

DataFixtures/ORM/ApplicationTrait.php
Migrations/pdo_pgsql/Version013.php

This PR update the default route of some application in order to update the NMM composer.json https://github.com/CanalTP/NMM/pull/423

Update default route

---

Tests/Selenium/SeleneseBlockTest.php

This PR fixes psr4 standard for autoloading in order to be compatible with future versions of composer
Issue link : BOT-2422

Fix namespace for Selenium Test
